version: "3.3"
services:
  mychallenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      challenge:
    container_name: challenge

networks:
  challenge:
    driver: bridge